# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Test: apiTest

  Stages:
  - Stage: build
    Jobs:
      - Job: build_installs
        steps:
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            packageType: 'sdk'
            version: '6.0'

        - task: UseDotNet@2
          displayName: 'Install .NET Runtime'
          inputs:
            packageType: 'runtime'
            version: '4.x'

        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

      - Job: build_job
        dependsOn: build_installs
        steps:
        - task: DotNetCoreCLI@2
        displayname: 'building'
        inputs:
          command: 'build'
          projects: 'group2project_jonathan_sean_mikael/*.sln'
          arguments: '--configuration $(buildConfiguration)'

  # - Stage: test
  #   Jobs:
  #     - Job: test_job
  #       steps:
  #       - task: DotNetCoreCLI@2
  #         inputs:
  #           command: 'test'
  #           projects: '''**/*Tests/*.csproj'''
  #           arguments: '''--configuration $(buildConfiguration)'''
  #           testRunTitle: 'API Test'
  
  # - Stage: publish
  #   Jobs:
  #     - Job: pubish_job
  #       steps:
  #         - task: DotNetCoreCLI@2
  #           inputs:
  #             command: 'publish'
  #             publishWebProjects: true
  #             modifyOutputPath: false