CREATE TABLE shop.Accounts
(
	AccountId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	FName NVARCHAR (25) NOT NULL,
	LName NVARCHAR (25) NOT NULL,
	IsAdmin BIT NOT NULL,
	Email NVARCHAR (50),
	Password NVARCHAR (15) NOT NULL,
	Address NVARCHAR (MAX) NOT NULL
)

CREATE TABLE shop.Orders
(
	OrderId UNIQUEIDENTIFIER PRIMARY KEY ,
	FK_AccountId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES shop.Accounts(AccountId),
	OrderDate DATETIME NOT NULL,
	OrderAmount INT NOT NULL,
	OrderTotal MONEY NOT NULL
)

CREATE TABLE shop.Products
(
	ProductId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ProductName NVARCHAR (50) NOT NULL,
	PRoductColor NVARCHAR (50) NOT NULL,
	ProductAmount INT NOT NULL,
	ProductPrice MONEY NOT NULL,
	ProductSize SMALLINT NOT NULL
)

CREATE TABLE shop.JunctTable
(
	JunctId INT PRIMARY KEY IDENTITY (1, 1) NOT NULL,
	FK_OrderId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES shop.Orders(OrderId),
	FK_ProductId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES shop.Products(ProductId)
)